data_config:
  train_file: train.jsonl
  val_file: val.jsonl
  test_file: test.jsonl
  num_proc: 1

max_input_length: 512
max_output_length: 512
training_args:
  output_dir: ./output
  max_steps: 128
  learning_rate: 5e-4
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  dataloader_num_workers: 7 
  remove_unused_columns: false
  save_strategy: steps
  save_steps: 10
  log_level: info
  logging_strategy: steps
  logging_steps: 50
  evaluation_strategy: steps
  eval_steps: 50
  predict_with_generate: true
  fp16: true 
  gradient_accumulation_steps: 1
  generation_config:
    max_new_tokens: 256
peft_config:
  peft_type: LORA
  task_type: CAUSAL_LM
  r: 1
  lora_alpha: 128
  lora_dropout: 0.1
  target_modules: ["query_key_value"]